### ISSUE TITLE
Heavy bandwidth usage from `filter` and `fields` requests

### ISSUE THREAD

**Issue by nitech** [pdaleramirez/super-filter#12]
I notice that the `filter` and `fields` replies are very large. 

For example, this reply only contains about 40 new items, and still is 1,7 mb: 

![image](https://user-images.githubusercontent.com/1279436/94114426-a2c2d780-fe48-11ea-9046-553bf1763479.png)

When I inspect the response, I see it contains the entire objects (assets, variants) and not just specific attributes (specifically variants are cracy loaded with data):

![image](https://user-images.githubusercontent.com/1279436/94115450-0568a300-fe4a-11ea-95aa-f9463b918e10.png)

I tried the following code to `unset()` the data I don't want in the response, but alas, it didn't work. I assume this event happens before `variants` and `productImages` are populated. And to be honest, I should not query all that data in the first place. 

```php
// Create image transformations for images delivered to the Super Filter plugin
Event::on(SearchTypes::class, SearchTypes::EVENT_ITEM_ARRAY, function (ItemArrayEvent $event) {
    if (Craft::$app->getPlugins()->isPluginEnabled('commerce') == true) {
        $srcImage = $event->element->productImage->one();

        // found any?
        $imageUrl = "";
        if ($srcImage){

            // get focalpoint
            $focalPoint = $srcImage->getFocalPoint();
            if (!$focalPoint) {
                $focalPoint = "50% 50%";
            }

            // transform with imager
            $image = Imager::getInstance()->imager->transformImage($srcImage, [
                'width' => 400,
                'format' => 'jpg',
                'ratio' => 1/1,
                'allowUpscale' => false,
                'jpegQuality' => 90,
                'position' => $focalPoint,
                'interlace' => true
            ], null, null);
            $imageUrl = $image->url;                            
        }
        else {
            $imageUrl = "https://via.placeholder.com/400x400.png?text=Placeholder";
        }

        $event->item['productImageTransform'] = $imageUrl;

    }

    // remove some unnecessary data
    // doesn't work
    unset($event->item['variants']);
    unset($event->item['productImage']);
});
```

What is your suggestion in this case?

**Comment by nitech** [comment]
It helped when I commented out this line:

https://github.com/pdaleramirez/super-filter/blob/5e02bdb366626733b38e2d7e95c8fb404379c051/src/SuperFilter.php#L136

Now the `filter`-request is only 26k.

**Comment by pdaleramirez** [comment]
@nitech by default it returns all element attributes on search results so the recommendation is specify the attributes that you want to return. Stated here https://github.com/pdaleramirez/super-filter#recommendation this will optimize the search results.

**Comment by nitech** [comment]
I also commented out these lines: 

https://github.com/pdaleramirez/super-filter/blob/5e02bdb366626733b38e2d7e95c8fb404379c051/src/services/SearchTypes.php#L465-L472

And now I get exactly what I want out of the query (only the specific attributes I need to display the search result):

![image](https://user-images.githubusercontent.com/1279436/94141685-6ce41a00-fe6d-11ea-8b39-7911bb08a71f.png)

The size is down to a few k.

How should I go about if I only want certain attributes from the products?

**Comment by nitech** [comment]
Thanks @pdaleramirez. Now I understand why `productImages` was included in the results. 

However, I still need to get rid of `variants`. How do I do that without commenting out this line? 

https://github.com/pdaleramirez/super-filter/blob/5e02bdb366626733b38e2d7e95c8fb404379c051/src/SuperFilter.php#L136

**Comment by pdaleramirez** [comment]
@nitech I added a new version 1.1.80 so that you can have an option remove variants attribute instruction here https://github.com/pdaleramirez/super-filter#craft-commerce please update to 1.1.80 version

**Comment by nitech** [comment]
Nice, thanks. This solves my issue.
