### ISSUE TITLE
If you change your site's data structure, without changing your filter set up, the field types change

### ISSUE THREAD

**Issue by LucySparks** [pdaleramirez/super-filter#15]
Hi, it's me again, hoping you can help. 

There's no way to specify which field types (checkboxes, dropdowns etc..) are for which category/categories or tag. 

-----

The site originally has two categories, Type and Brand and no tags. 
Type was a checkbox list and Brand was a dropdown. I didn't specify this but I worked with it and it was fine. 

I added tags to blog posts---this is entirely removed from anything to do with the Super Filter. I did not change the Super filter settings. 

But seemingly just adding tags anywhere on the site changed the Super Filter: my second category (Brand) from a dropdown to a checkbox list, which isn't what I want. 
I built everything based on the assumption you could only filter for one brand at a time (dropdown), and a checkbox list means that's no longer the case and things are broken. 

-----

Is there anyway to specify which field type a given _selected_ search field uses?

Cheers, 
Lucy

**Comment by pdaleramirez** [comment]
@LucySparks Are you using Vue as your base template? If you are, are you wrapping only super-filter elements in the 
`<div id="search-app">` If you have form elements not related super filter, placed it outside the search-app div. Check out here https://github.com/pdaleramirez/super-filter#using-super-filter.

**Comment by LucySparks** [comment]
I am using the basic plain templates, no vue. Consequently, I haven't used `<div id="search-app">`

<img width="692" alt="Screen Shot 2020-11-09 at 9 15 57 am" src="https://user-images.githubusercontent.com/37562179/98486262-35d69600-226c-11eb-83d4-61a08206c30d.png">

**Comment by pdaleramirez** [comment]
@LucySparks Have you tested using `craft.superFilter.close()`? You should only put super filter elements between `craft.superFilter.setup('plain')` and `craft.superFilter.close()`

**Comment by LucySparks** [comment]
Thanks for getting back to me

By "Super filter elements" you mean super filter form elements? That is the case with my code. 

I'm a little unclear on exactly where you recommend I put the `{{ craft.superFilter.close() }}` tag but regardless if I add the `{{ craft.superFilter.close() }}` tag immediately after the search fields and sort fields---or even after the items and pagination---it doesn't change my second category field from checkboxes back to the dropdown they used to be. 

I think it might be worth noting I didn't change the templates before or after adding tags to blog posts, so I would be surprised to find that changing the templates would fix the issue.  

Is it possible to add a way to specify whether you want the search fields to be AND or OR with themselves? As in whether you can only have one or multiple values for a given filtering parameter. Then you can, in a round about way,  nominate whether the fields are checkbox lists (Self - AND) or dropdowns (self - OR).

Let me know, thanks in advance

**Comment by pdaleramirez** [comment]
@LucySparks Would it be possible to email me your sql dump and your template files. I want to see the issue where adding tags changes the dropdown input. 

There are relationship settings you can test how you want it to work.

**Comment by LucySparks** [comment]
Thanks for looking into it, I've emailed.
