### ISSUE TITLE
CP blank after install

### ISSUE THREAD

**Issue by green17** [pdaleramirez/super-filter#18]
CP is blank after install, would this be a php 7.4 problem maybe?

**Comment by pdaleramirez** [comment]
@green17 What version of cms and super-filter are you using? This should run okay in PHP 7.4. Can you paste the error on dev console or the error logs here?

**Comment by green17** [comment]
@pdaleramirez in the logs there was a problem with plugin 'Control Panel Nav 3.0.15' when this was uninstalled it now shows the CP, sorry for the hassel. :-)
