### ISSUE TITLE
Range filtering

### ISSUE THREAD

**Issue by piotrpog** [pdaleramirez/super-filter#3]
Most of webshops have some kind of range filters, usually price range.

Such feature is must have for such plugin :)

**Comment by pdaleramirez** [comment]
I will see if i can release that feature this month.

**Comment by jeffaglenn** [comment]
I'm coming up on a need for this as well! Glad to know it's being worked on. Thank you and super impressed with the plugin so far.

**Comment by nitech** [comment]
@pdaleramirez how are things progressing with this one?

**Comment by pdaleramirez** [comment]
@nitech @jeffaglenn @piotrpog This feature is now up in version `1.3.0`. A new Price Range Field option shows up when product search type is selected on setup.
