### ISSUE TITLE
Server Error when loading /admin/super-filter/setup-search

### ISSUE THREAD

**Issue by muplatformdev** [pdaleramirez/super-filter#4]
500 error when it tries to load/reach:
index.php?p=admin/actions/element-indexes/get-elements&v=1583947315067

Everything else seems to work, but I can see saved searches there either. 

Any ideas? 

I've tried uninstalling/re-installing but it didn't do anything.

**Comment by pdaleramirez** [comment]
I need more information about this error. Can you post the error logs here.

**Comment by pdaleramirez** [comment]
@muplatformdev can you try update your super-filter version to `1.0.6.1` and let me know if that fixed your issue?
