### ISSUE TITLE
Error while setting up search

### ISSUE THREAD

**Issue by E2design** [pdaleramirez/super-filter#5]
I'm not able to setup a search. Only half of the screen seems visible. When I hit the save button the errors appear. (see screenshot)
![Schermafbeelding 2020-03-16 om 14 16 12 (2)](https://user-images.githubusercontent.com/5907530/76762306-5576f680-6791-11ea-9dc1-d25cfc121600.png)

The install "example data" also don't seem to work.

Craft: 3.4.9
Super-filter: 1.0.6

**Comment by pdaleramirez** [comment]
@E2design would you send the error logs? or can you go to Network -> Preview on dev tools and paste the error here

**Comment by pdaleramirez** [comment]
@E2design i have release new version to try to fix your issue. Can you update super-filter version to `1.0.6.1` and let me know if that fixed your issue?
