### ISSUE TITLE
Can I use this with users?

### ISSUE THREAD

**Issue by tom-byrom** [pdaleramirez/super-filter#6]
Hi mate,
This looks really awesome! Can this be used with users? Or anyway to allow it to be used with users?

The use case would be to have a page that returns all users and allows you to to filter users by their custom fields such as, skill, location etc

Many thanks
Tom

EDIT:

Doesn't look like it's possible, I've just been playing with it but can only access entries and categories, I can't select users as the element? 

Anyway to easily include this? The rest of the plugin looks great but I would really need to use this for users.

**Comment by pdaleramirez** [comment]
Unfortunately, this feature is still not yet supported,  i will let you know when a new release for this feature is up. @tom-byrom
