### ISSUE TITLE
Custom Fields not showing in Sort Fields

### ISSUE THREAD

**Issue by jeffaglenn** [pdaleramirez/super-filter#7]
None of my custom fields are showing up in the Sort Fields section when creating a new filter. In the example attached I would like to both filter and sort by bedrooms and bathrooms. I've tried a few different field types (radio buttons, dropdown, number) and nothing seems to show up in the sort column. Am I missing something?

<img width="525" alt="Screen Shot 2020-05-15 at 11 52 50 AM" src="https://user-images.githubusercontent.com/34280463/82076087-e17aa100-96a2-11ea-8a88-16deaba67297.png">

**Comment by pdaleramirez** [comment]
Not all fields are actually shown in the sort section. Fields that are sort-able are only shown and can be used

**Comment by jeffaglenn** [comment]
I installed the example data and tried again and still none of the custom fields are sortable?

![Screen Shot 2020-05-20 at 2 21 10 PM](https://user-images.githubusercontent.com/34280463/82488312-49ffbe80-9aa5-11ea-947f-9831f6e28493.png)

**Comment by jeffaglenn** [comment]
Any idea on why some fields wouldn't show for sorting? Is there anything I can test?

**Comment by pdaleramirez** [comment]
Not all fields are shown in the sorting section. Only the fields that has sorting support
