### ISSUE TITLE
Option not load app.css

### ISSUE THREAD

**Issue by jeffaglenn** [pdaleramirez/super-filter#8]
Is there an option not to load app.css for the plain" template or is still it needed for functionality purposes? I don't need bootstrap and it's interfering with my styles. I have commented the file out in VueAsset.php but it will get overwritten when an update is released.

**Comment by pdaleramirez** [comment]
@jeffaglenn Please update to v1.1.4 and then use override template. Override the `plain/setup.twig`
Then remove the code in the twig file 
```
{% do view.registerAssetBundle("pdaleramirez\\superfilter\\web\\assets\\VueAsset") %}
```

**Comment by jeffaglenn** [comment]
Thanks! I tried it the other day and it didn't work but just tried again and did what it was supposed to do. I must have missed something the first time.
